Add `HomeView` content for when there are no pets
Apple-Developer-Residency-IFCE/LoveMyCapibara pull request #10
Opened 2023-05-31 22:58 UTC by tiago-vargas

2023-06-01 21:42 UTC, Maurrici requested changes

2023-06-01 21:42 UTC, Maurrici commented on LoveMyCapibara/LoveMyCapibara/Views/Scenes/HomeView.swift
> +let emptyPetList: [PetModel] = []
Colocar esta variável dentro da struct de Preview, para isso ela deverá ser uma variável com o modificador static

2023-06-02 00:01 UTC, gusholz reviewed
Após a mudança sugerida pelo Maurício creio que vai ficar funcional. Sugiro fazer a atualização visual do componente para utilizar o FontManager e as cores apropriadas.

2023-06-02 21:04 UTC, gusholz approved these changes
👍

2023-06-02 21:47 UTC, tiago-vargas commented
<img width="312" alt="Screenshot 2023-06-02 at 18 41 49" src="https://github.com/Apple-Developer-Residence-IFCE/LoveMyCapibara/assets/78927143/9b16fda1-9c30-4779-991c-e2bd34ba8fbd">

Usei o asset como PDF porque o SVG renderizava na preview com uma imagem errada, diferente da que aparecia nos arquivos.

2023-06-05 22:30 UTC, Maurrici approved these changes
Alterações foram realizadas

2023-06-06 17:06 UTC, MagnoCarta requested changes

2023-06-06 17:06 UTC, MagnoCarta commented on LoveMyCapibara/LoveMyCapibara/Views/Scenes/HomeView.swift
> +        if pets.isEmpty {
Logica de negocios esta na view , talvez seja interessante criar uma ViewModel para gerencia-la?

2023-06-06 17:06 UTC, MagnoCarta commented on LoveMyCapibara/LoveMyCapibara/Views/Scenes/HomeView.swift
> +    var pets: [PetModel]
Pets é uma var, talvez não funcione ou não atualize após modificar a variável

2023-06-06 17:06 UTC, MagnoCarta commented on LoveMyCapibara/LoveMyCapibara/Views/Scenes/ContentView.swift
> +            HomeView(pets: [])
Considerando que vocês precisam separar a lógica de receber os pets em algum lugar, talvez aqui não seja o melhor lugar para isso

2023-06-06 17:06 UTC, MagnoCarta commented on LoveMyCapibara/LoveMyCapibara/Views/Scenes/HomeView.swift
> +    var pets: [PetModel]
Continua como uma var, talvez um state ou published em uma viewmodel fosse mais interessante, aqui será impossível de testar

2023-06-06 17:06 UTC, MagnoCarta commented on LoveMyCapibara/LoveMyCapibara/Views/Scenes/HomeView.swift
> +        if pets.isEmpty {
Acredito que a Homeview necessite de uma Viewmode ou alguma camada extral para gerenciar toda a lógica, ou então sera impossível testar no futuro, ainda não existe, pets, vazio e talvez ate  navegação.

2023-06-06 17:23 UTC, Maurrici commented on LoveMyCapibara/LoveMyCapibara/Views/Scenes/HomeView.swift
> +        if pets.isEmpty {
Magno, a lógica da View-Model está na branch que eu e o @Jwinny estamos trabalhando, lá a view-Model ja apresenta um variável computada para passar para a HomeView

2023-06-07 21:27 UTC, MagnoCarta approved these changes

2023-06-07 22:16 UTC, merged