Feature/pet detailed view
Apple-Developer-Residency-IFCE/LoveMyCapibara pull request #13
Opened 2023-06-06 22:30 UTC by gusholz

View de detalhes do pet adicionada

2023-06-07 22:19 UTC, Maurrici requested changes

2023-06-07 22:19 UTC, Maurrici commented on LoveMyCapibara/LoveMyCapibara/Views/Scenes/PetDetailsView/Subviews/PetAttributes.swift
> +                .font(FontManager.poppinsBold(size: 16))
- Adequar a fonte dos atributos

A fonte dos atributos não deveria ser Bold, o design mostra uma fonte regular

2023-06-07 22:19 UTC, Maurrici commented on LoveMyCapibara/LoveMyCapibara/Views/Scenes/PetDetailsView/Subviews/PetAttributes.swift
> +            Image("Icon Macho _ Default")
- Tornar a imagem dinâmica 

A imagem de gênero deveria ser dinâmica com base no gênero do pet

2023-06-07 22:24 UTC, Jwinny requested changes
As funcionalidades estão ótimas, o único problema encontrado foi o do "peso" nos textos do petAtributes. Pois deveriam ser Poppins regular e a cor deveria ser o background: #15181D;
- Versão da Branch
<img width="78" alt="Captura de Tela 2023-06-07 às 19 21 52" src="https://github.com/Apple-Developer-Residence-IFCE/LoveMyCapibara/assets/56833799/598abd7e-56b2-483d-a41a-93be514b24bc">

- Versão do design
<img width="78" alt="Captura de Tela 2023-06-07 às 19 23 03" src="https://github.com/Apple-Developer-Residence-IFCE/LoveMyCapibara/assets/56833799/894429d2-7399-4922-b4d0-4451b9f2e513">

2023-06-08 00:10 UTC, gusholz commented on LoveMyCapibara/LoveMyCapibara/Views/Scenes/PetDetailsView/Subviews/PetAttributes.swift
> +                .font(FontManager.poppinsBold(size: 16))
Resolvido 👍

2023-06-12 23:00 UTC, tiago-vargas approved these changes

2023-06-12 23:32 UTC, Maurrici approved these changes

2023-06-14 00:25 UTC, MagnoCarta approved these changes
Resolve os conflitos \o

2023-06-14 00:25 UTC, MagnoCarta commented on LoveMyCapibara/LoveMyCapibara/Views/Scenes/Settings/Subviews/ThemeOption.swift
> +            if selectedID == id {
Testa fzr um ternario pra ver se fica bom \o

2023-06-14 22:22 UTC, Jwinny approved these changes
👍🏻
Ótimo, só é necessário corrigir esse conflito nas referências do project, antes do merge.

2023-06-14 23:54 UTC, Jwinny approved these changes

2023-06-14 23:56 UTC, merged