Feature/delete button
Apple-Developer-Residency-IFCE/LoveMyCapibara pull request #16
Opened 2023-06-12 22:03 UTC by gusholz

Botão componentizado criado

2023-06-13 21:37 UTC, tiago-vargas approved these changes

2023-06-13 22:22 UTC, Maurrici requested changes

2023-06-13 22:22 UTC, Maurrici commented on LoveMyCapibara/LoveMyCapibara/Views/ReusableComponents/CustomButton.swift
> +    }
As estilizações deveriam ser aplicadas em um View do tipo Text que recebe a String buttonLabel, ai essa View Text seria passada em Button.

2023-06-13 22:23 UTC, gusholz commented on LoveMyCapibara/LoveMyCapibara/Views/ReusableComponents/CustomButton.swift
> +    }
Resolvido 👍

2023-06-13 22:23 UTC, Maurrici approved these changes

2023-06-13 22:26 UTC, tiago-vargas approved these changes

2023-06-14 00:19 UTC, Jwinny approved these changes
ok

2023-06-14 00:31 UTC, MagnoCarta requested changes

2023-06-14 00:31 UTC, MagnoCarta commented on LoveMyCapibara/LoveMyCapibara/Views/Scenes/PetDetailsView/Subviews/LabelsOfPet.swift
> +            Text("Nome")
Um padrão de repetição de código , talvez haja um jeito de aprimorar

2023-06-14 00:31 UTC, MagnoCarta commented on LoveMyCapibara/LoveMyCapibara/Views/Scenes/PetDetailsView/Subviews/PetAttributes.swift
> +                .font(FontManager.poppinsBold(size: 16))
Mesmo que falei

2023-06-14 20:50 UTC, gusholz commented on LoveMyCapibara/LoveMyCapibara/Views/Scenes/PetDetailsView/Subviews/LabelsOfPet.swift
> +            Text("Nome")
é nessa branch mesmo Magno 🤔? Fiz a correção mas creio que seria na branch feature/PetDetailedView

2023-06-14 20:57 UTC, MagnoCarta approved these changes

2023-06-14 20:58 UTC, merged