Feature/fields add pet
Apple-Developer-Residency-IFCE/LoveMyCapibara pull request #17
Opened 2023-06-13 21:39 UTC by Maurrici

- Tela de adicionar:
<img width="452" alt="image" src="https://github.com/Apple-Developer-Residence-IFCE/LoveMyCapibara/assets/53577592/14b91bce-7b2b-46f3-9147-6e5287cbefa4">

- Tela de editar: ( OBS.: Não contém o botão de excluir pois é uma task separada)
<img width="452" alt="image" src="https://github.com/Apple-Developer-Residence-IFCE/LoveMyCapibara/assets/53577592/36cca248-3257-48e4-b4ef-311ae0f8c3b7">

2023-06-13 22:33 UTC, tiago-vargas approved these changes

2023-06-13 23:02 UTC, gusholz approved these changes
👍

2023-06-14 21:55 UTC, Jwinny requested changes
### Retirar comentários 
#### encontra-se nas `linhas 10 e 12` do arquivo `EditPetView`

<img width="561" alt="Captura de Tela 2023-06-14 às 18 36 07" src="https://github.com/Apple-Developer-Residence-IFCE/LoveMyCapibara/assets/56833799/81ee172b-913e-4ab0-8be0-66e33242404c">

### Corrigir a cor do nome do pet na Edit Pet View
<img width="287" alt="Captura de Tela 2023-06-14 às 18 43 05" src="https://github.com/Apple-Developer-Residence-IFCE/LoveMyCapibara/assets/56833799/602c548e-9fc6-44a3-91e7-d1a7350e31d0">

### Redundância no código
#### A variável já é um Optional, acredito que atribuir o nil é uma redundância que pode ser limpa.
Encontra-se nas `linhas 13 e 19` do `FormViewModel`
<img width="658" alt="Captura de Tela 2023-06-14 às 18 49 23" src="https://github.com/Apple-Developer-Residence-IFCE/LoveMyCapibara/assets/56833799/bca4acb2-6fda-44f3-b8ea-0d9250b3d544">

2023-06-15 00:14 UTC, gusholz approved these changes

2023-06-15 00:22 UTC, tiago-vargas approved these changes

2023-06-15 00:33 UTC, Jwinny approved these changes
Está ótimo 👍🏻

2023-06-15 00:33 UTC, merged