Button weight and Date picker
Apple-Developer-Residency-IFCE/LoveMyCapibara pull request #21
Opened 2023-06-19 22:07 UTC by Jwinny

Components to use in add and edit View Pet

2023-06-19 23:22 UTC, gusholz requested changes
Percebi que a fonte (Linha 31) do ButtonWeightPicker não está utilizando o FontManager na chamada da fonte 
Realizando essa substituição simples vai resolver o problema
De
      `  .font(Font.custom("Poppins-Regular", size: 16))
`
Para
` .font(FontManager.poppinsRegular(size: 16))`

Notei também que o display do peso esta mostrando somente os Kg e não os Kg com as gramas. Percebi que o design tava desse jeito também e comuniquei a Laís, que comentou que era um erro e que já foi ajustado.
De qualquer modo, o código atualizado seria 
De
`Button("\(kg) kg"){
`

Para
`Button("\(kg), \(gram) kg"){
`

2023-06-20 20:40 UTC, Maurrici requested changes
Comentários:
- Lembrar de criar a branch com o prefixo **feature** (ex.: feature/nome_da_branch)
- Quando fizer o PR verificar os conflitos, se algum PR tiver sido aceito depois de você ter criado a branch é necessário fazer um merge com a develop para obter as alterações e resolver os possíveis conflitos

Mudanças necessárias:

- O Componente de peso e o de data devem ser responsáveis por receber um estado e alterar o valor deste. Em ambos os componentes os estados estão sendo criados dentro do próprio componente, ou seja quem está chamando não recebe o valor alterado, para isso os componentes deveriam fazer um @Binding, logo quem os chama passa o estado e eles manipulam esse estado.

1.  No caso do componente DatePickerView basta alterar a linha 11 de: **@State var birthdayDate : Date = Date.now** para **@Binding var birthdayDate : Date = Date.now**

2. No caso do ButtonWeightPicker, como definido na modelagem o peso do Pet será um Double, logo é esperado que o componente receba um @Binding de um Double, a lógica atual de utilizar dois Inteiros( kg e gramas) pode ser mantida sem problemas mas é necessário que ao receber um Double o componente seja responsável por obter a parte inteira e decimal e colocar nesses inteiros e quando o houver alterações nesses inteiros eles devem ser combinados para atualizar o valor do Double

2023-06-21 00:32 UTC, tiago-vargas approved these changes

2023-06-21 00:34 UTC, Maurrici approved these changes

2023-06-21 21:06 UTC, gusholz approved these changes

2023-06-21 21:07 UTC, merged