Feature/calendar graph
Apple-Developer-Residency-IFCE/LoveMyCapibara pull request #48
Opened 2023-07-20 00:46 UTC by Maurrici

https://github.com/Apple-Developer-Residence-IFCE/LoveMyCapibara/assets/53577592/dc51ca00-1ba6-45f1-a336-c146f6bc3fdb

2023-07-20 20:13 UTC, gusholz commented on LoveMyCapibara/LoveMyCapibara/Views/ReusableComponents/FormView/Subviews/InputPicker.swift
Acho que da pra diminuir um pouco esse range kkk
`InputPicker(label: "Castrado", value: .constant(2023), options: Array(Range(1900...2100)))`

2023-07-20 20:14 UTC, gusholz approved these changes
🔝

2023-07-21 21:32 UTC, ravi2612 commented on LoveMyCapibara/LoveMyCapibara/Views/ReusableComponents/CalendarGraph/CalendarGraph.swift
> +
retirar linha em branco

2023-07-21 21:37 UTC, ravi2612 requested changes, later dismissed

2023-07-21 21:37 UTC, ravi2612 commented on LoveMyCapibara/LoveMyCapibara/Views/ReusableComponents/CalendarGraph/CalendarViewModel.swift
> +                let date = calendar.date(byAdding: .day, value: day, to: startDate)!
variável muito grande, extrair para uma função e retirar o force unwrapes e tratar os valores optionals

2023-07-21 21:50 UTC, IsaiasDimitri approved these changes

2023-07-25 19:38 UTC, gusholz approved these changes

2023-07-25 21:00 UTC, IsaiasDimitri approved these changes

2023-07-25 21:07 UTC, merged