Add tab view
Apple-Developer-Residency-IFCE/LoveMyCapibara pull request #5
Opened 2023-05-26 21:27 UTC by tiago-vargas

I added `HomeView.swift` and `SettingsView.swift` as stubs to make the tab view compile.

2023-05-26 22:10 UTC, gusholz approved these changes
👍

2023-05-26 22:23 UTC, Maurrici approved these changes

2023-05-26 22:25 UTC, Jwinny requested changes
- Falta adicionar o retângulo que delimita a TabBar.
- Trocar os textos dos botões ( Home -> Pets | Settings -> Configurações )

A funcionalidade está boa.

2023-05-29 23:51 UTC, Jwinny approved these changes
Ótimo 👍🏻
Só faltou a linha superior - uma opção que eu achei seria usar o overlay, similar à como o @gusholz usou para a criação da "box" do card. Segue abaixo uma sugestão de implementação. 
✌🏻
# Sugestão:
```
TabView{
...
}.overlay(
    RoundedRectangle(cornerRadius: 0)
        .stroke(Color.gray, lineWidth: 1)
        .frame(height: 1)
        .offset(y: -1)
)

```

2023-05-29 23:51 UTC, merged

2023-05-31 17:04 UTC, MagnoCarta reviewed
show