PetCardView created
Apple-Developer-Residency-IFCE/LoveMyCapibara pull request #6
Opened 2023-05-26 22:27 UTC by gusholz

Pet Card View component created

2023-05-29 20:29 UTC, Jwinny requested changes
O card está ótimo é necessário apenas adicionar o fundo a ele.
Fui verificar como o card estava nos dois modos e pude notar que ha a ausência do background no card.

# Sugestão inicial
.background(
        RoundedRectangle(cornerRadius: 8)
            .fill(Color.white)
            .overlay(
                RoundedRectangle(cornerRadius: 8)
                    .stroke(Color.gray, lineWidth: 1.4)
            )
    )

2023-05-30 20:46 UTC, MagnoCarta requested changes
Tente pelo menos ir atras de alguma outra solução em que não utilize UIScreen.main

2023-05-30 20:46 UTC, MagnoCarta commented on LoveMyCapibara/LoveMyCapibara/Views/ReusableComponents/PetCardView.swift
> +        .frame(width: UIScreen.main.bounds.width * 0.8,alignment: .leading)
Será que usar UIScreen é a melhor solução?

2023-05-30 21:32 UTC, gusholz commented on LoveMyCapibara/LoveMyCapibara/Views/ReusableComponents/PetCardView.swift
> +        .frame(width: UIScreen.main.bounds.width * 0.8,alignment: .leading)
Consertado 😉

2023-05-30 21:33 UTC, Jwinny approved these changes
ok

2023-05-30 21:33 UTC, Maurrici approved these changes

2023-05-30 22:10 UTC, tiago-vargas approved these changes

2023-05-31 17:03 UTC, MagnoCarta approved these changes

2023-05-31 19:45 UTC, merged